### ISSUE TITLE
TypeError: 'Polygon' object is not iterable

### ISSUE THREAD

**Issue by killer10607** [maxnoe/plz_plot#2]
error in core.py. While i tried to use the example i`ve got the following error:
`Traceback (most recent call last):
  File "F:/Desktop-Share/plz_plot-master/examples/plot_plz_areas.py", line 46, in <module>
    vmax=2.5e4,
  File "F:\Desktop-Share\plz_plot-master\plz_plot\core.py", line 39, in plot_plz_data
    col, repeat = build_patch_collection(recs)
  File "F:\Desktop-Share\plz_plot-master\plz_plot\core.py", line 15, in build_patch_collection
    for geom in rec.geometry:
TypeError: 'Polygon' object is not iterable`

**Comment by dcambie** [comment]
See PR #3 for a fix to this issue ;)

**Comment by maxnoe** [comment]
Fixed by @dcambie  in 33ff474
